
package org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ConsultaInformacionService", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://14.240.4.208:8083/ConsultaInformacionService.svc?wsdl")
public class ConsultaInformacionService
    extends Service
{

    private final static URL CONSULTAINFORMACIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException CONSULTAINFORMACIONSERVICE_EXCEPTION;
    private final static QName CONSULTAINFORMACIONSERVICE_QNAME = new QName("http://tempuri.org/", "ConsultaInformacionService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://14.240.4.208:8083/ConsultaInformacionService.svc?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONSULTAINFORMACIONSERVICE_WSDL_LOCATION = url;
        CONSULTAINFORMACIONSERVICE_EXCEPTION = e;
    }

    public ConsultaInformacionService() {
        super(__getWsdlLocation(), CONSULTAINFORMACIONSERVICE_QNAME);
    }

    public ConsultaInformacionService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONSULTAINFORMACIONSERVICE_QNAME, features);
    }

    public ConsultaInformacionService(URL wsdlLocation) {
        super(wsdlLocation, CONSULTAINFORMACIONSERVICE_QNAME);
    }

    public ConsultaInformacionService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONSULTAINFORMACIONSERVICE_QNAME, features);
    }

    public ConsultaInformacionService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConsultaInformacionService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IConsultaInformacionService
     */
    @WebEndpoint(name = "BasicHttpBinding_IConsultaInformacionService")
    public IConsultaInformacionService getBasicHttpBindingIConsultaInformacionService() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IConsultaInformacionService"), IConsultaInformacionService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IConsultaInformacionService
     */
    @WebEndpoint(name = "BasicHttpBinding_IConsultaInformacionService")
    public IConsultaInformacionService getBasicHttpBindingIConsultaInformacionService(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IConsultaInformacionService"), IConsultaInformacionService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONSULTAINFORMACIONSERVICE_EXCEPTION!= null) {
            throw CONSULTAINFORMACIONSERVICE_EXCEPTION;
        }
        return CONSULTAINFORMACIONSERVICE_WSDL_LOCATION;
    }

}
