
package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import org.datacontract.schemas._2004._07.wsser.ConsultaConsolidadoResp;
import org.datacontract.schemas._2004._07.wsser.ConsultaDatoResp;
import org.datacontract.schemas._2004._07.wsser.ConsultaFirmaResp;
import org.datacontract.schemas._2004._07.wsser.ConsultaFotoResp;
import org.datacontract.schemas._2004._07.wsser.ConsultaRequest;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IConsultaInformacionService", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    com.microsoft.schemas._2003._10.serialization.ObjectFactory.class,
    org.datacontract.schemas._2004._07.wsser.ObjectFactory.class,
    org.tempuri.ObjectFactory.class
})
public interface IConsultaInformacionService {


    /**
     * 
     * @param req
     * @return
     *     returns org.datacontract.schemas._2004._07.wsser.ConsultaDatoResp
     */
    @WebMethod(action = "http://tempuri.org/IConsultaInformacionService/consultarDatos")
    @WebResult(name = "consultarDatosResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "consultarDatos", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConsultarDatos")
    @ResponseWrapper(localName = "consultarDatosResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConsultarDatosResponse")
    public ConsultaDatoResp consultarDatos(
        @WebParam(name = "req", targetNamespace = "http://tempuri.org/")
        ConsultaRequest req);

    /**
     * 
     * @param req
     * @return
     *     returns org.datacontract.schemas._2004._07.wsser.ConsultaFirmaResp
     */
    @WebMethod(action = "http://tempuri.org/IConsultaInformacionService/consultarFirma")
    @WebResult(name = "consultarFirmaResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "consultarFirma", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConsultarFirma")
    @ResponseWrapper(localName = "consultarFirmaResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConsultarFirmaResponse")
    public ConsultaFirmaResp consultarFirma(
        @WebParam(name = "req", targetNamespace = "http://tempuri.org/")
        ConsultaRequest req);

    /**
     * 
     * @param req
     * @return
     *     returns org.datacontract.schemas._2004._07.wsser.ConsultaFotoResp
     */
    @WebMethod(action = "http://tempuri.org/IConsultaInformacionService/consultarFoto")
    @WebResult(name = "consultarFotoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "consultarFoto", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConsultarFoto")
    @ResponseWrapper(localName = "consultarFotoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConsultarFotoResponse")
    public ConsultaFotoResp consultarFoto(
        @WebParam(name = "req", targetNamespace = "http://tempuri.org/")
        ConsultaRequest req);

    /**
     * 
     * @param req
     * @return
     *     returns org.datacontract.schemas._2004._07.wsser.ConsultaConsolidadoResp
     */
    @WebMethod(action = "http://tempuri.org/IConsultaInformacionService/consultarConsolidado")
    @WebResult(name = "consultarConsolidadoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "consultarConsolidado", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConsultarConsolidado")
    @ResponseWrapper(localName = "consultarConsolidadoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConsultarConsolidadoResponse")
    public ConsultaConsolidadoResp consultarConsolidado(
        @WebParam(name = "req", targetNamespace = "http://tempuri.org/")
        ConsultaRequest req);

}
